package InterfazGrafica;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class VentanaNuevaOferta extends JFrame{
    private JPanel panelPrincipal;
    private JTextField txtVacante;
    private JScrollPane scrollDescripcion;
    private JTextArea txtAreaDescripcion;
    private JTextField txtSalario;
    private JTextField txtVacantes;
    private JButton btnCrear;
    private JButton btnCancelar;
    private JCheckBox checkDomingo;
    private JCheckBox checkLunes;
    private JCheckBox checkMartes;
    private JCheckBox checkMiercoles;
    private JCheckBox checkJueves;
    private JCheckBox checkViernes;
    private JCheckBox checkSabado;
    private JComboBox comboInicioLunes;
    private JComboBox comboInicioMartes;
    private JComboBox comboInicioMiercoles;
    private JComboBox comboInicioJueves;
    private JComboBox comboInicioViernes;
    private JComboBox comboInicioSabado;
    private JComboBox comboInicioDomingo;
    private JComboBox comboFinLunes;
    private JComboBox comboFinMartes;
    private JComboBox comboFinMiercoles;
    private JComboBox comboFinJueves;
    private JComboBox comboFinViernes;
    private JComboBox comboFinSabado;
    private JComboBox comboFinDomingo;
    
    private int idEmpleador;
    
    public VentanaNuevaOferta(int idEmpleador){
        setVisible(true);
        setSize(500,500);
        setTitle("Nueva oferta");
        setLocationRelativeTo(null);
        this.idEmpleador=idEmpleador;
        inicializarComponentes();
        establecerPropiedades();
    }
    
    public void inicializarComponentes(){
        add(panelPrincipal = new JPanel());
        GridBagLayout gridBagPrincipal = new GridBagLayout();
        panelPrincipal.setLayout(gridBagPrincipal);
        GridBagConstraints constantes = new GridBagConstraints();
        constantes.insets= new Insets(5, 5, 5, 5);
        constantes.anchor= GridBagConstraints.NORTHWEST;
        constantes.gridx = 0;
        constantes.gridy = 0;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.NONE;
        JLabel lblVacante = new JLabel("Vacante: ");
        panelPrincipal.add(lblVacante, constantes);
        constantes.gridx = 1;
        constantes.gridy = 0;
        constantes.gridwidth = 4;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.HORIZONTAL;
        panelPrincipal.add(txtVacante= new JTextField(), constantes);
        JLabel lblDescripcion = new JLabel("Descripción: ");
        constantes.weighty=1;
        constantes.gridx=0;
        constantes.gridy=1;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.NONE;
        panelPrincipal.add(lblDescripcion, constantes);
        constantes.weighty=0;
        constantes.gridx=1;
        constantes.gridy=1;
        constantes.gridwidth = 4;
        constantes.gridheight = 5;
        constantes.fill = GridBagConstraints.BOTH;
        panelPrincipal.add(scrollDescripcion = new JScrollPane(txtAreaDescripcion = new JTextArea()), constantes);
        JLabel salario = new JLabel("Salario: ");
        constantes.gridx=0;
        constantes.gridy=6;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.NONE;
        panelPrincipal.add(salario, constantes);
        constantes.gridx=1;
        constantes.gridy=6;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.HORIZONTAL;
        panelPrincipal.add(txtSalario = new JTextField(), constantes);
        JLabel lblOrden = new JLabel("Especificar periodo");
        constantes.gridx=1;
        constantes.gridy=7;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.NONE;
        panelPrincipal.add(lblOrden, constantes);
        JLabel lblVacantes = new JLabel("Vacantes: ");
        constantes.gridx=0;
        constantes.gridy=8;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(lblVacantes, constantes);
        constantes.gridx=1;
        constantes.gridy=8;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.HORIZONTAL;
        panelPrincipal.add(txtVacantes= new JTextField(), constantes);
        JLabel lblHorario = new JLabel("Horario");
        constantes.gridx=2;
        constantes.gridy=6;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        constantes.fill = GridBagConstraints.NONE;
        panelPrincipal.add(lblHorario, constantes);
        constantes.gridx=2;
        constantes.gridy=7;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkLunes = new JCheckBox("Lunes"), constantes);
        constantes.gridx=3;
        constantes.gridy=7;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioLunes = new JComboBox();
        comboInicioLunes.addItem("10:00");
        panelPrincipal.add(comboInicioLunes, constantes);
        constantes.gridx=4;
        constantes.gridy=7;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinLunes = new JComboBox();
        comboFinLunes.addItem("20:00");
        panelPrincipal.add(comboFinLunes, constantes);
        constantes.gridx=2;
        constantes.gridy=8;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkMartes = new JCheckBox("Martes"), constantes);
        constantes.gridx=3;
        constantes.gridy=8;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioMartes = new JComboBox();
        comboInicioMartes.addItem("10:00");
        panelPrincipal.add(comboInicioMartes, constantes);
        constantes.gridx=4;
        constantes.gridy=8;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinMartes = new JComboBox();
        comboFinMartes.addItem("20:00");
        panelPrincipal.add(comboFinMartes, constantes);
        constantes.gridx=2;
        constantes.gridy=9;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkMiercoles = new JCheckBox("Miercoles"), constantes);
        constantes.gridx=3;
        constantes.gridy=9;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioMiercoles = new JComboBox();
        comboInicioMiercoles.addItem("10:00");
        panelPrincipal.add(comboInicioMiercoles, constantes);
        constantes.gridx=4;
        constantes.gridy=9;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinMiercoles = new JComboBox();
        comboFinMiercoles.addItem("20:00");
        panelPrincipal.add(comboFinMiercoles, constantes);
        constantes.gridx=2;
        constantes.gridy=10;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkJueves = new JCheckBox("Jueves"), constantes);
        constantes.gridx=3;
        constantes.gridy=10;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioJueves = new JComboBox();
        comboInicioJueves.addItem("10:00");
        panelPrincipal.add(comboInicioJueves, constantes);
        constantes.gridx=4;
        constantes.gridy=10;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinJueves = new JComboBox();
        comboFinJueves.addItem("20:00");
        panelPrincipal.add(comboFinJueves, constantes);
        constantes.gridx=2;
        constantes.gridy=11;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkViernes = new JCheckBox("Viernes"), constantes);
        constantes.gridx=3;
        constantes.gridy=11;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioViernes = new JComboBox();
        comboInicioViernes.addItem("10:00");
        panelPrincipal.add(comboInicioViernes, constantes);
        constantes.gridx=4;
        constantes.gridy=11;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinViernes = new JComboBox();
        comboFinViernes.addItem("20:00");
        panelPrincipal.add(comboFinViernes, constantes);
        constantes.gridx=2;
        constantes.gridy=12;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkSabado = new JCheckBox("Sabado"), constantes);
        constantes.gridx=3;
        constantes.gridy=12;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioSabado = new JComboBox();
        comboInicioSabado.addItem("10:00");
        panelPrincipal.add(comboInicioSabado, constantes);
        constantes.gridx=4;
        constantes.gridy=12;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinSabado = new JComboBox();
        comboFinSabado.addItem("20:00");
        panelPrincipal.add(comboFinSabado, constantes);
        constantes.gridx=2;
        constantes.gridy=13;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(checkDomingo = new JCheckBox("Sabado"), constantes);
        constantes.gridx=3;
        constantes.gridy=13;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboInicioDomingo = new JComboBox();
        comboInicioDomingo.addItem("10:00");
        panelPrincipal.add(comboInicioDomingo, constantes);
        constantes.gridx=4;
        constantes.gridy=13;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        comboFinDomingo = new JComboBox();
        comboFinDomingo.addItem("20:00");
        panelPrincipal.add(comboFinDomingo, constantes);
        constantes.gridx=3;
        constantes.gridy=15;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(this.btnCrear = new JButton("Crear"), constantes);
        constantes.gridx=4;
        constantes.gridy=15;
        constantes.gridwidth = 1;
        constantes.gridheight = 1;
        panelPrincipal.add(this.btnCancelar = new JButton("Cancelar"), constantes);
    }
    public void establecerPropiedades(){
        this.txtAreaDescripcion.setWrapStyleWord(true);
        this.txtAreaDescripcion.setLineWrap(true);
    }
}
